### PR TITLE
(CISC-1018) Update metadata support for Puppet 7

### PR DESCRIPTION
**Pull request by da-ar**
While the module installs and run fine as a dependency or explicitly via code manager, anything that checks the metadata complains that this will not work with 2019.x which runs Puppet 6. 

Bumped further for the incoming Puppet 7 2020.x release. 

Manually tested with Comply, the gem happy runs our tasks.

### CODE REVIEW

**Comment by da-ar** [comment]
This will require a release of the Gem when approved

**Comment by lucywyman** [comment]
Hello! I don't think we need all of the PDK files, this should just update the metadata.json to bump the Puppet version.

**Comment by da-ar** [comment]
> Hello! I don't think we need all of the PDK files, this should just update the metadata.json to bump the Puppet version.

The PR was originally just that, but as the tests failed i updated the module to the latest PDK to pick up the right configuration for Puppet modules. https://travis-ci.com/github/puppetlabs/puppetlabs-ruby_task_helper/jobs/472723717

**Comment by lucywyman** [comment]
Ok - that is failing because our `.rubocop.yml` needs to be updated to Ruby 2.5 instead of 2.3. https://github.com/puppetlabs/puppetlabs-ruby_task_helper/blob/master/.rubocop.yml#L2 Would you be ok with doing that here, or would you rather I put up a PR with that change?

**Comment by da-ar** [comment]
> Ok - that is failing because our `.rubocop.yml` needs to be updated to Ruby 2.5 instead of 2.3. https://github.com/puppetlabs/puppetlabs-ruby_task_helper/blob/master/.rubocop.yml#L2 Would you be ok with doing that here, or would you rather I put up a PR with that change?

I have removed the changes made to support the latest PDK and changed the rubocop ruby version manually to 2.5

As you can see this fails and additional work IS required for this module. I highly recommend accepting my initial PR.

**Comment by davidmalloncares** [comment]
@lucywyman is there any chance we can just go with the original change that fixed the issue and was passing in CI? If that doesn't sound like a plan then maybe we can just raise an issue and leave it with you guys?

**Comment by lucywyman** [comment]
You can definitely raise an issue with us and we'll address it.

**Comment by davidmalloncares** [comment]
cheers @lucywyman , @da-ar do you want to walk away from this PR, raise an issue and point the user to that issue so they can track?

**Comment by lucywyman** [comment]
https://github.com/puppetlabs/puppetlabs-ruby_task_helper/pull/14 Fixes CI, I can add hte Puppet bump there or you can rebase off of it. It should get merged later today once Tom is in to review.

**Comment by lucywyman** [comment]
Ok, fixed in #15 should be released later today!

**Pull request closed without merging**
